import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.context.annotation.Configuration
/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
@SpringBootApplication(scanBasePackages = ['com.surveysampling.bowling'] )
@Configuration
class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
