package com.surveysampling.bowling.spring;

import org.springframework.boot.*;
import org.springframework.boot.autoconfigure.*;

;

/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
@SpringBootApplication(scanBasePackages = {"com.surveysampling.bowling"})
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
